### ISSUE TITLE
[BUG] make postinstall manticore indexing table dailydelta1

### ISSUE THREAD

**Issue by Vertux** [jsuto/piler#76] opened 2024-06-22 16:02 UTC
I have done a fresh installation on Debian 12.5 using the installation manual. When it comes to `make postinstall` I get a fatal error - it looks like it is related to [#1348](https://bitbucket.org/jsuto/piler/issues/1348/some-improvements-to-docker-documentation) even though I am not using Docker.

**Hint:** I have to say, that I had to to run `make postinstall` twice - I know this is not recommended, but I did not want to start from scratch. I dropped the mySQL user and database before, I do not know if it is sufficient. 
It would be very helpful to have a list of the cleanup jobs required to safely run `make postinstall' again.

```
[.....]
indexing table 'dailydelta1'...
FATAL: table 'dailydelta1': cannot apply kill list to myself: killlist_target=main1:kl, main2:kl, main3:kl, main4:kl, dailydelta1:kl

make: *** [Makefile:129: postinstall] Fehler 1
```
**Piler version:**
```
piler 1.4.5, Janos SUTO <sj@acts.hu>

Build Date: Sat Jun 22 11:17:13 CEST 2024
ldd version: ldd (Debian GLIBC 2.36-9+deb12u7) 2.36
gcc version: gcc version 12.2.0 (Debian 12.2.0-14)
OS: Linux mailpiler 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
Configure command: ./configure --localstatedir=/var --with-database=mariadb
MySQL client library version: 3.4.0
Extractors: /usr/bin/pdftotext /usr/bin/catdoc /usr/bin/catppt /usr/bin/xls2csv /usr/bin/unrtf /usr/bin/tnef libzip
```

**Comment by jsuto** [comment] 2024-06-22 17:09
Duplicate of #68

**Closed by jsuto** 2024-06-22 17:09 UTC
Labels: duplicate

**Comment by Vertux** [comment] 2024-06-22 18:30
Thank you for pointing me in the right direction.
